//Redux
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const GET_PLAYLISTS = 'GET_PLAYLISTS';
export const RESET_STATE = 'RESET_STATE';
export const GET_PLAYLIST_ITEMS = 'GET_PLAYLIST_ITEMS';
export const NEXT_VIDEO = 'NEXT_VIDEO';
export const GOTO_VIDEO = 'GOTO_VIDEO';
export const CHANGE_PLAY_STATE = 'CHANGE_PLAY_STATE';
export const INCREMENT_TIME = 'INCREMENT_TIME';
export const RESET_CLOCK = 'RESET_CLOCK';
export const CHANGE_VIDEO_LENGTH = 'CHANGE_VIDEO_LENGTH';
export const FLIP_NEXT = 'FLIP_NEXT';
export const CHANGE_VIDEO_START = 'CHANGE_VIDEO_START';
export const SHOW_MODAL = 'SHOW_MODAL';

//Epic
export const FETCH_PLAYLISTS = 'FETCH_PLAYLISTS';
export const FETCH_PLAYLIST_ITEMS = 'FETCH_PLAYLIST_ITEMS';
