//Redux
//root
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const CHANGE_VIDEO_LENGTH = 'CHANGE_VIDEO_LENGTH';
export const FLIP_NEXT = 'FLIP_NEXT';
export const SHOW_MODAL = 'SHOW_MODAL';
export const RESET_STATE = 'RESET_STATE';
export const RESET_CALL_NEXT = 'RESET_CALL_NEXT';

//playlistItems
export const SET_PLAYLIST_ITEMS = 'SET_PLAYLIST_ITEMS';
export const NEXT_VIDEO = 'NEXT_VIDEO';
export const GOTO_VIDEO = 'GOTO_VIDEO';
export const CHANGE_VIDEO_START = 'CHANGE_VIDEO_START';

//clock
export const RESET_CLOCK = 'RESET_CLOCK';
export const INCREMENT_TIME = 'INCREMENT_TIME';
export const CHANGE_PLAY_STATE = 'CHANGE_PLAY_STATE';

//createUser
export const FLIP_SHOW_DIALOG = 'FLIP_SHOW_DIALOG';
export const CHANGE_USERNAME = 'CHANGE_USERNAME';
export const SET_SERVER_ID = 'SET_SERVER_ID';

//playlists
export const SET_CURRENT_PLAYLIST = 'SET_CURRENT_PLAYLIST';
export const SET_PLAYLIST_INDEX = 'SET_PLAYLIST_INDEX';
export const SET_YOUTUBE_PLAYLISTS = 'SET_YOUTUBE_PLAYLISTS';
export const SET_SERVER_PLAYLISTS = 'SET_SERVER_PLAYLISTS';
export const ADD_SERVER_PLAYLIST = 'ADD_SERVER_PLAYLIST';
export const REMOVE_SERVER_PLAYLIST = 'REMOVE_SERVER_PLAYLIST';

//Epic
//playlists
export const FETCH_YOUTUBE_PLAYLISTS = 'FETCH_YOUTUBE_PLAYLISTS';
export const FETCH_SERVER_PLAYLISTS = 'FETCH_SERVER_PLAYLISTS';
export const SAVE_PLAYLIST = 'SAVE_PLAYLIST';
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST';

//playlistItems
export const FETCH_YOUTUBE_PLAYLIST_ITEMS = 'FETCH_YOUTUBE_PLAYLIST_ITEMS';
export const FETCH_SERVER_PLAYLIST_ITEMS = 'FETCH_SERVER_PLAYLIST_ITEMS';
export const CHANGE_SERVER_VIDEO_START = 'CHANGE_SERVER_VIDEO_START';

//clock
export const START_TIME = 'START_TIME';
export const END_TIME = 'END_TIME';

//createUser
export const CREATE_USER = 'CREATE_USER';
